.TH f77 1L "October 21, 1994" "POSIX"
.SH NAME
f77 - Fortran 77 compiler
.SH SYNOPSIS
.B f77
[options] file ...
.SH DESCRIPTION
.B f77
is a Fortran 77 compiler that translates Fortran 77 source code to
executable programs. It is implemented as a frontend for the AT&T
Laboratories and Bellcore
.B f2c
Fortran to C translator, working with the SAS/C C compiler
version 6.58. The compiler accepts the following types of
file arguments:
.PP
Arguments that end with .f are compiled as Fortran 77 source files.
If each source compiles successfully, its corresponding object file is
left in the current directory in a file whose name is that of the
source, with .o substituted for .f.
.PP
Arguments that end with .c are assumed to be C source files, and are
compiled, producing .o files.
.PP
Arguments that end with .o are passed on to the linker (see
the SAS documentation for slink) to be linked into the final program.
.PP
Arguments that end with .lib are taken to be standard AmigaDOS linker
libraries of .o files to be searched in the order they appear.
.PP
f77 accepts the following options:
.TP
.B -c
Suppress linking and produce an object (.o) file from each source file.
.TP
.B -g
Generate information needed by the symbolic SAS CodeProbe debugger.
.TP
.RI -o " outfile"
Name the output file resulting from linking
.I outfile
instead of the default file name a.out.
.TP
.B -v
Enable the verbose mode, producing a step-by-step
description of the compilation process.
.TP
.B -w
Suppress all warning messages from
.B f2c .
.TP
.B -w66
Enable warnings about Fortran 66 features used.
.TP
.B -C
Enable array subscript range checking.
.TP
.B -I2
Make default size of integers and logicals INTEGER*2 and LOGICAL*2.
.TP
.B -I4
Make default size of integers and logicals INTEGER*4 and LOGICAL*4.
.TP
.RI -I " dir"
Add directory
.I dir
to the include search path.
.TP
.RI -L " dir"
Add directory
.I dir
to the library search path.
.TP
.RI -D " name"
Define preprocessor macro
.I name
with value 1.
.TP
.RI -D " name=value"
Define preprocessor macro
.I name
with value
.IR value .
.TP
.RI -U " name"
Undefine preprocessor macro
.IR name .
.TP
.RI -l " name"
Search the library lib:name.lib. Libraries specified by this option
are searched after the ones given directly.
.TP
.B -O
Enable the SAS C global optimizer.
.TP
.B -S
Translate the named Fortran source files and leave the C language
output in corresponding files whose names are suffixed with .c
(no .o files are created).
.TP
.B -u
Force types of identifiers to be implicitly undeclared (same as
specifying IMPLICIT NONE).
.TP
.B -onetrip
Execute any DO loop at least once.
.TP
.B -noext
Do not accept any extensions to Fortran 77, like DO - END DO.
.TP
.B +B
Treat the backslash character as a C-like escape character.
.TP
.B +U
Distinguish uppercase and lowercase (make case significant).
Keywords must be lowercase. Also accepted as
.BR -U .
.SH FILES
.nf
f2c                    Fortran to C translator
sc                     SAS/C compiler
slink                  SAS/C linker
include:f2c.h          f2c header file
lib:f2c.lib            f2c runtime library
lib:scmnb.lib          SAS/C math library
lib:scnb.lib           SAS/C standard library
lib:c.o                C runtime startup code
.fi
.SH "SEE ALSO"
f2c(1)
.SH AUTHOR
.B f77
is freely redistributable and was written by
Torsten Poulin Nielsen (torsten@diku.dk) who
also ported
.B f2c
and welcomes suggestions and bug reports.
.PP
This implementation provides POSIX-compliant Fortran 77 compilation
on AmigaDOS systems using the f2c Fortran to C translator.
