# $Header: /home/amb/cxref/RCS/Makefile.config 1.5 1997/08/25 09:24:14 amb Exp $
#
# C Cross Referencing & Documentation tool. Version 1.4a.
#
# Configuration Makefile.
#
# Written by Andrew M. Bishop
#
# This file Copyright 1995,96 Andrew M. Bishop
# It may be distributed under the GNU Public License, version 2, or
# any higher version.  See section COPYING of the GNU Public license
# for conditions under which this file may be redistributed.
#

# Instead of editing one of the Makefiles, edit this one.

# The location to install the programs.
# (in subdirectories bin and man/man1 .)

INSTDIR=/usr/local

# The installation program.
# (if you don't have a BSD style install, use ./install.sh .)

INSTALL=install -c

# The C compiler and flags

CC=gcc
CFLAGS=-O2

# The linker and flags

LD=gcc
LDFLAGS=

# The Yacc program

YACC=bison -y -l

# The Lex Program

LEX=flex -L

# The Perl program
# (If you do not have perl, leave it blank.)

PERL=perl

# The LaTeX and dvips programs
# (If you do not have LaTeX or dvips, leave them blank.)

LATEX=latex
DVIPS=dvips

# The LaTeX page size.
# (A4 or US only.)

LATEX_PAGE=A4
