(*
 *	This file was automaticly generated by OBumpRev 0.4.
 *	DO NOT EDIT THIS FILE!
 *)

<* STANDARD- *> <* INITIALISE- *> <* MAIN- *>

MODULE	pwdRev;

IMPORT	SYSTEM;

CONST	version	*= 1;
	revision*= 0;
	date	*= "23.12.95";
	vers	*= "pwd 1.0";
	vString	*= "pwd 1.0 (23.12.95)\r\n";
	versTag	*= "$VER: pwd 1.0 (23.12.95)\r\n";

BEGIN	(* Make sure that version string is visible *)
	SYSTEM.PUTREG (0, SYSTEM.ADR (versTag))
END	pwdRev.
