#
# C Cross Referencing & Documentation tool. Version 1.3
#
# CPP Configuration Makefile.
#
# Generated by config-cpp
#
# This file Copyright 1995,96 Andrew M. Bishop
# It may be distributed under the GNU Public License, version 2, or
# any higher version.  See section COPYING of the GNU Public license
# for conditions under which this file may be redistributed.
#

# The predefined macros and answers to questions
# e.g PREDEFINES = -D__GNUC__=2 -D__GNUC_MINOR__=6 -Dunix -D__unix__ -D__unix -Asystem(unix)

PREDEFINES = -D__GNUC__=2 -D__GNUC_MINOR__=7 -Dmc68000 -Damiga -Damigaos -Damigados -DMCH_AMIGA -DAMIGA -D__chip=__attribute__((chip)) -D__saveds=__attribute__((saveds)) -D__interrupt=__attribute__((interrupt)) -D__stackext=__attribute__((stackext)) -D__regargs=__attribute__((regparm)) -D__stdargs=__attribute__((stkparm)) -D__aligned=__attribute__((aligned(4))) -D__mc68000__ -D__amiga__ -D__amigaos__ -D__amigados__ -D__MCH_AMIGA__ -D__AMIGA__ -D__chip=__attribute__((chip)) -D__saveds=__attribute__((saveds)) -D__interrupt=__attribute__((interrupt)) -D__stackext=__attribute__((stackext)) -D__regargs=__attribute__((regparm)) -D__stdargs=__attribute__((stkparm)) -D__aligned=__attribute__((aligned(4))) -D__mc68000 -D__amiga -D__amigaos -D__amigados -D__MCH_AMIGA -D__AMIGA -Asystem(amigaos) -Asystem(amigados) -Acpu(m68k) -Amachine(m68k) -Dixemul -D__ixemul__ -D__ixemul

# The predefined include search directories

INCLUDE_DIR1 = /ade/local/include
INCLUDE_DIR2 = /ade/m68k-amigaos/include
INCLUDE_DIR3 = /ade/lib/gcc-lib/m68k-amigaos/2.7.2.1/include

# Set if replacements for bzero, bcmp, bcopy and index, rindex are needed

SVR4_STRINGS = 0

# The status of the configuration
# Set CONFIG_STATUS to a null value if cxref-cpp is to be built.

CONFIG_STATUS =
